### ISSUE TITLE
Am2904 - setµX implementation highly mistakable

### ISSUE THREAD

**Issue by Haspamelodica** [MaisiKoleni/Am2900ME#5]
These methods are implemented like this:
`µN = μN & 1;`
where the first µN refers to the field, and the second one refers to the parameter.
This works, because the character for 'µ' used in parameter names differs from the one used in field names. Without syntax highlighting, it can be challenging to notice this...

**Comment by MaisiKoleni** [comment]
Thanks for the remark; I already found it in the Am2910 and fixed that but overlooked that there were more.
