### ISSUE TITLE
D-Bus not working for some combinations of source/target

### ISSUE THREAD

**Issue by Haspamelodica** [MaisiKoleni/Am2900ME#6]
When loading BZ (_BZ_LD is L), the data source can't be Y-MUX (_DBUS is DB).
For example: Konst=0x1234; Am2901_Src=DZ; _DBUS=DB; _BZ_LD=L (see attached file):
java.lang.IllegalArgumentException: cannot load pc with no data signal

[minstrs.txt](https://github.com/MaisiKoleni/Am2900ME/files/2927441/minstrs.txt)

**Comment by MaisiKoleni** [comment]
Fixed in the follow-on project Mograsim, cannot be fixed with Am2900ME simulation architecture within reasonable effort for such a rare use case.
